name: Whois
version: 0.1
main: com.deaboy.whois.Whois
website:
author: Deaboy
commands:
    whois:
        usage: Use /whois [player] to get info on a player
        description: Gets any saved information on the given player
        aliases: [who]
    stats:
        usage: User /stat [player] to get the stats of that player
        description: Gets any saved statistics on the given player
        aliases: [statistics,stat]